import os
import sys

from PIL import Image

im_me = Image.open('img/source_img/car_me.jpg')
im_thanos_car = Image.open('img/source_img/thanos_car.png')
im_ironman = Image.open('img/source_img/ironman.png')
im_en = Image.open('img/source_img/car_enemy.jpg')
im_en0 = Image.open('img/source_img/en0.png')
im_en1 = Image.open('img/source_img/en1.png')
im_en2 = Image.open('img/source_img/en2.png')
im_en3 = Image.open('img/source_img/en3.png')
im_sto1 = Image.open('img/source_img/space_stone.png')
im_sto2 = Image.open('img/source_img/reality_stone.png')
im_sto3 = Image.open('img/source_img/power_stone.png')
im_sto4 = Image.open('img/source_img/mind_stone.png')
im_sto5 = Image.open('img/source_img/time_stone.png')
im_sto6 = Image.open('img/source_img/soul_stone.png')
im_En0 = Image.open('img/source_img/hawkeye.png')
im_En1 = Image.open('img/source_img/hulk.png')
im_En2 = Image.open('img/source_img/thor.png')
im_En3 = Image.open('img/source_img/black.png')
im_En4 = Image.open('img/source_img/spider.png')
im_En5 = Image.open('img/source_img/cap.png')
im_En6 = Image.open('img/source_img/iron.png')

new_im_me = im_me.resize((50, 100), Image.ANTIALIAS)
new_im_thanos_car = im_thanos_car.resize((50, 100), Image.ANTIALIAS)
new_im_en = im_en.resize((50, 100), Image.ANTIALIAS)
new_im_en0 = im_en0.resize((50, 100), Image.ANTIALIAS)
new_im_en1 = im_en1.resize((50, 100), Image.ANTIALIAS)
new_im_en2 = im_en2.resize((50, 100), Image.ANTIALIAS)
new_im_en3 = im_en3.resize((50, 100), Image.ANTIALIAS)
new_im_sto1 = im_sto1.resize((50, 50), Image.ANTIALIAS)
new_im_sto2 = im_sto2.resize((50, 50), Image.ANTIALIAS)
new_im_sto3 = im_sto3.resize((50, 50), Image.ANTIALIAS)
new_im_sto4 = im_sto4.resize((50, 50), Image.ANTIALIAS)
new_im_sto5 = im_sto5.resize((50, 50), Image.ANTIALIAS)
new_im_sto6 = im_sto6.resize((50, 50), Image.ANTIALIAS)
new_im_En0 = im_En0.resize((50, 100), Image.ANTIALIAS)
new_im_En1 = im_En1.resize((50, 100), Image.ANTIALIAS)
new_im_En2 = im_En2.resize((50, 100), Image.ANTIALIAS)
new_im_En3 = im_En3.resize((50, 100), Image.ANTIALIAS)
new_im_En4 = im_En4.resize((50, 100), Image.ANTIALIAS)
new_im_En5 = im_En5.resize((50, 100), Image.ANTIALIAS)
new_im_En6 = im_En6.resize((50, 100), Image.ANTIALIAS)
new_im_ironman = im_ironman.resize((800, 600), Image.ANTIALIAS)

new_im_en.save("img/source_img/car_enemy.png")
new_im_me.save("img/source_img/car_me.png")
new_im_thanos_car.save("img/source_img/thanos_car.png")
new_im_en0.save("img/source_img/en0.png")
new_im_en1.save("img/source_img/en1.png")
new_im_en2.save("img/source_img/en2.png")
new_im_en3.save("img/source_img/en3.png")
new_im_sto1.save("img/source_img/stone1.png")
new_im_sto2.save("img/source_img/stone2.png")
new_im_sto3.save("img/source_img/stone3.png")
new_im_sto4.save("img/source_img/stone4.png")
new_im_sto5.save("img/source_img/stone5.png")
new_im_sto6.save("img/source_img/stone6.png")
new_im_En0.save("img/source_img/Ene0.png")
new_im_En1.save("img/source_img/Ene1.png")
new_im_En2.save("img/source_img/Ene2.png")
new_im_En3.save("img/source_img/Ene3.png")
new_im_En4.save("img/source_img/Ene4.png")
new_im_En5.save("img/source_img/Ene5.png")
new_im_En6.save("img/source_img/Ene6.png")
new_im_ironman.save("img/source_img/ironman.png")
